#-------------------------------
# General Site Settings
title: Zolan
logo: logo.svg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll
author:
  name: Prakhar Kumar


#-------------------------------
# intro Settings
# images wiil be fetched from the image/ folder
intro:
  say-hello: Couldn't find it Anywhere?
  bio:  'At Axotico we build upon your imagination to bring your ideas to life. We fabricate ideas proposed by you into products to make your life hassle-free and to transform your dreams into reality, delivered right at your doorstep.'
  slideshow:
    - img: intro/01.jpg
      alt: 'one'
      title: title1
      cap: caption 1
    - img: intro/01.jpg
      alt: two
      title: title2
      cap: caption 2  
    - img: intro/01.jpg
      alt: three
      title: title3
      cap: caption 3


#-------------------------------
# Three Simple Steps
simplesteps:
  - image: 02.jpg
    alt: 'A'
    title: Where there's a will, there's <Strong><a href="#">Axotico!</a></strong>
    desc: We are a team of passionate and trained professionals who understands your hurdles and offer you the best, wisely curated solution chosen through deliberation. We are the world's first and only company to solve problems in multiple domains by applying disruptive thinking to problems by embarking on a revolutionary path for innovation.
  
  - image: 02.jpg
    alt: 'B'
    title: <strong><a>Hassle-Free</a></strong> solutions
    desc: 'Here at Axotico we animate your initiative by embracing your ideas while offering insights and provide you with customized products at your comfort. We deal with an endless range of products encompassing sectors like housing, industries, hotels, restaurants, and so on.'
  
  - image: 02.jpg
    alt: 'C'
    title: <strong><a>Magic</a></strong> at your doorstep
    desc: 'We bring you the best and convenient solution at your doorstep all over India. <br /> So order now in single or bulk quantities and be assured to have a hassle-free experience delivered at the comfort of your own home.'
  
#-------------------------------
# Team Details
team:
  - name: Kay Garland
    pic: team_members/01.jpg
    position: Lead Designer
    social:
      - title: linkedin
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #

  - name: Kay Garland
    pic: team_members/01.jpg
    position: Lead Designer
    social:
      - title: twitter-square
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #
  - name: Kay Garland
    pic: team_members/01.jpg
    position: Lead Designer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #

#-------------------------------
# contact Us Settings
contactus:
  head: Let’s Talk Together
  intro: 'Shoot us an e-mail or give us a call. '
  contacts:
    - icon: map
      details: '<a href="#">aisjbdnasijdb ONE</a>'
    - icon: phone
      details: 'aisjbdnasijdb TWO'
    - icon: envelope-open
      details: 'aisjbdnasijdb THREE'

#-------------------------------
# WorkFlow Settings

workflow:
  intro: 'Personal Care to each Request!'
  flow_end: 'BE PART<br/>OF OUR<br/>STORY!'
  timelinedata:
    - img: team_members/01.jpg
      head1: 'Test Head'
      head2: 'heading 1'
      subhead: '1017-18'
      desc: 'Large content Here lsdifbvsdiu bbsdiu vbpsdiuvd npsdiuvnpidsuvni pdsuncpsidj cpiusdncpius dpcu sdpi c'
    - img: team_members/01.jpg
      head1: 'Test Head 2'
      head2: 'heading 1'
      subhead: '1017-18'
      desc: 'Large content Here lsdifbvsdiu bbsdiu vbpsdiuvd npsdiuvnpidsuvni pdsuncpsidj cpiusdncpius dpcu sdpi c'
    - img: team_members/01.jpg
      head1: 'Test Head 3'
      head2: 'heading 1'
      subhead: '1017-18'
      desc: 'Large content Here lsdifbvsdiu bbsdiu vbpsdiuvd npsdiuvnpidsuvni pdsuncpsidj cpiusdncpius dpcu sdpi c'

#-------------------------------
# Footer Settings
# useful_links_cols can have value as 1 or 2

footer:
  logo_href: '#'
  desc: 'Company vision Here'
  contacts:
    - icon: map
      head: Find Us
      details: 'Address'
    - icon: phone
      head: Call Us
      details: '+91-9876543210'
    - icon: envelope-open
      head: Mail Us
      details: 'mailus@example.com'
  social:
      - icon: twitter twitter-bg
        url: #
      - icon: facebook facebook-bg
        url: #
  useful_links_cols: 2
  useful_links:
    - name: 'ONE'
      link: #
    - name: 'TWO'
      link: #
  subscribe_desc: 'Don’t miss to subscribe to our new feeds, kindly fill the form below.'


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e