#-------------------------------
# General Site Settings
title: Zolan
logo: logo.svg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll

#-------------------------------
# contact Us Settings
contactus:
  head: Let’s Talk Together
  intro: 'Shoot us an e-mail or give us a call. '
  contacts:
    - icon: map
      details: '<a href="#">aisjbdnasijdb ONE</a>'
    - icon: phone
      details: 'aisjbdnasijdb TWO'
    - icon: envelope-open
      details: 'aisjbdnasijdb THREE'
  

#-------------------------------
# intro Settings
# images wiil be fetched from the image/ folder
intro:
  say-hello: Hello, I’m <strong>Alex Rodriguez</strong>
  bio: Designs, talks, and writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share design tutorials, free resources and inspiration. Loves <a href="#">music</a> & riding his bicycle.
  slideshow:
    - img: intro/01.jpg
      alt: 'one'
      title: title1
      cap: caption 1
    - img: intro/01.jpg
      alt: two
      title: title2
      cap: caption 2  
    - img: intro/01.jpg
      alt: three
      title: title3
      cap: caption 3


#-------------------------------
# Three Simple Steps
simplesteps:
  - image: 02.jpg
    alt: 'A'
    title: Where there's a will, there's <Strong><a href="#">Axotico!</a></strong>
    desc: 'So order now in single or bulk quantities and be assured to have a hassle-free experience delivered at the comfort of your own home.'
  - image: 02.jpg
    alt: 'B'
    title: RANDOM TITLE 2
    desc: Random Description 2
  - image: 02.jpg
    alt: 'C'
    title: RANDOM TITLE 3
    desc: Random Description 3
  
#-------------------------------
# Team Details
team:
  - name: Kay Garland
    pic: team_mambers/01.jpg
    position: Lead Designer
    social:
      - title: linkedin
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #

  - name: Kay Garland
    pic: team_mambers/01.jpg
    position: Lead Designer
    social:
      - title: twitter-square
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #
  - name: Kay Garland
    pic: team_mambers/01.jpg
    position: Lead Designer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #



     

#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e